# Generated by Django 4.1 on 2022-10-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings_watched',
            field=models.ManyToManyField(blank=True, related_name='watching_users', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.listing'),
        ),
    ]
