# Generated by Django 4.1 on 2022-10-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_listings_watched_alter_comment_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
